[tool.poetry]
name = "sccp"
version = "0.1.0"
description = "Single cell analysis across conditions using PARAFAC2."
authors = ["Andrew Ramirez", "Aaron Meyer <git@asmlab.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "^1.24"
scipy = "^1.11"
scikit-learn = "^1.3"
seaborn = "^0.12.2"
pandas = "^2.0"
tensorly = "0.8.0"
tqdm = "^4.65.0"
h5netcdf = "^1.1.0"
anndata = "^0.9.1"
torch = "2.0.0"
numba = "^0.57.0"
datashader = "^0.15"
umap-learn = {version = "0.5.3", extras = ["plot"]}
mygene = "^3.2.2"
gseapy = "^1.0.4"
scib = "^1.1.3"
rpy2 = "^3.5.12"
anndata2ri = "^1.1"
scvi = "^0.6.8"
scvi-tools = "^0.20.3"
scanorama = "^1.7.3"

[tool.poetry.dev-dependencies]
pytest = "^7.3"
pytest-cov = "^3.0.0"
mypy = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "sccp.figures.common:genFigure"