[tool.poetry]
name = "sccp"
version = "0.1.0"
description = "Single cell analysis across conditions using PARAFAC2."
authors = ["Andrew Ramirez", "Aaron Meyer <git@asmlab.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "^1.24"
scipy = "^1.11"
scikit-learn = "^1.3"
seaborn = "^0.12.2"
pandas = "2.0.3"
tensorly = "0.8.1"
tqdm = "^4.65.0"
h5netcdf = "^1.1.0"
anndata = "^0.9.2"
torch = "2.0.0"
numba = "^0.58.0"
datashader = "^0.15"
umap-learn = { version = "^0.5.4", extras = ["plot"] }
mygene = "^3.2.2"
gseapy = "^1.0.4"
openpyxl = "^3.1.2"
parafac2 = { git = "https://github.com/meyer-lab/parafac2.git", rev = "81de3749330fede88c3f93c069532e438c98b1f7" }
scanpy = "^1.9.5"

[tool.poetry.dev-dependencies]
pytest = "^7.3"
pytest-cov = "^3.0.0"
mypy = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "sccp.figures.common:genFigure"