[tool.poetry]
name = "sccp"
version = "0.1.0"
description = ""
authors = ["Andrew Ramirez", "Aaron Meyer <git@asmlab.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.24.1"
scipy = "^1.10.0"
scikit-learn = "^1.2.0"
seaborn = "^0.11.2"
pyarrow = "^7.0.0"
tensorly = "0.8.0"
xarray = "^2022.12.0"
igraph = "^0.9.11"
louvain = "^0.7.1"
leidenalg = "^0.8.10"
tensorly-viz = "^0.1.7"
tqdm = "^4.64.1"
torch = "^1.13.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
mypy = "^0.950"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "sccp.figures.common:genFigure"