[tool.poetry]
name = "sccp"
version = "0.1.0"
description = "Single cell analysis across conditions using PARAFAC2."
authors = ["Andrew Ramirez", "Aaron Meyer <git@asmlab.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "^1.24"
scipy = "^1.10"
scikit-learn = "^1.2"
seaborn = "^0.12.2"
pandas = "^2.0"
tensorly = "0.8.0"
tqdm = "^4.65.0"
h5netcdf = "^1.1.0"
anndata = "^0.8.0"
torch = "2.0.0"
numba = "0.57.0rc1"
umap-learn = "^0.5.3"
mygene = "^3.2.2"

[tool.poetry.dev-dependencies]
pytest = "^7.3"
pytest-cov = "^3.0.0"
mypy = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "sccp.figures.common:genFigure"