[tool.poetry]
name = "sccp"
version = "0.1.0"
description = "Single cell analysis across conditions using PARAFAC2."
authors = ["Andrew Ramirez", "Aaron Meyer <git@asmlab.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "^1.25"
scipy = "^1.11.3"
scikit-learn = "^1.3"
seaborn = "^0.13"
pandas = "2.1.1"
tensorly = { git = "https://github.com/meyer-lab/tensorly.git", rev = "ad5eb92622da21a0ff3c1a02626ef2ba071d9510" }
h5netcdf = "^1.1.0"
anndata = "^0.10"
datashader = "^0.15"
mygene = "^3.2.2"
gseapy = "^1.0.4"
scanpy = "^1.9.5"
pacmap = "^0.7.1"
leidenalg = "^0.10.1"
tqdm = "^4.66.1"
cupy-cuda12x = "^12.2.0"
setuptools = "^68.2.2"

[tool.poetry.dev-dependencies]
pytest = "^7.4"
pytest-cov = "^4.1"
mypy = "^1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "sccp.figures.common:genFigure"