[tool.poetry]
name = "sccp"
version = "0.1.0"
description = "Single cell analysis across conditions using PARAFAC2."
authors = ["Andrew Ramirez", "Aaron Meyer <git@asmlab.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
numpy = "^1.25"
scipy = "^1.11"
scikit-learn = "^1.3"
seaborn = "^0.12.2"
pandas = "2.0.3"
tensorly = { git = "https://github.com/tensorly/tensorly.git", rev = "357aa6649ae481ec635792d3e9a86513c6870108" }
h5netcdf = "^1.1.0"
anndata = "^0.9.2"
numba = "^0.58.0"
datashader = "^0.15"
mygene = "^3.2.2"
gseapy = "^1.0.4"
openpyxl = "^3.1.2"
scanpy = "^1.9.5"
pacmap = "^0.7.1"
leidenalg = "^0.10.1"

[tool.poetry.dev-dependencies]
pytest = "^7.3"
pytest-cov = "^3.0.0"
mypy = "^1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]                                                           
fbuild = "sccp.figures.common:genFigure"