"""
Property-based invariant tests for the core factorization/compression
primitives.

These tests fuzz shapes, ranks, and random seeds with Hypothesis rather than
relying only on a handful of hand-picked examples, to surface edge cases
(rank == 1, a single condition, near-degenerate columns, ...) that
example-based tests tend to miss. Each test asserts a mathematical property
that must hold for *any* valid input, not just the specific arrays checked
elsewhere in the suite.
"""

import anndata
import numpy as np
import pytest
from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st
from hypothesis.extra.numpy import arrays

from ..factorization import (
    canonical_component_signs,
    correct_conditions,
    match_components_across_ranks,
    order_components_by_energy,
)
from ..opq import OPQQuantizer

# Bounded, finite, non-degenerate floats: avoids the near-zero-norm columns
# that would make sign/cosine-similarity assertions numerically meaningless.
_finite_floats = st.floats(
    min_value=-100.0,
    max_value=100.0,
    allow_nan=False,
    allow_infinity=False,
    width=32,
)

_slow_settings = settings(
    max_examples=15, deadline=None, suppress_health_check=[HealthCheck.too_slow]
)


def _nonzero_column_matrix(n_rows: int, n_cols: int):
    """A matrix strategy in which every column has norm bounded away from 0,
    generated by adding a fixed unit spike to each column of a random
    matrix (cheaper and more reliable than a `.filter()` on norm)."""
    return arrays(
        dtype=np.float64, shape=(n_rows, n_cols), elements=_finite_floats
    ).map(lambda C: C + np.eye(n_rows, n_cols) * 10.0)


@given(
    n_rows=st.integers(min_value=1, max_value=12),
    n_cols=st.integers(min_value=1, max_value=6),
    data=st.data(),
)
@_slow_settings
def test_canonical_component_signs_idempotent_and_positive_max(n_rows, n_cols, data):
    """Signing is idempotent, and always leaves the largest-magnitude entry
    of each column positive -- the defining property from the docstring."""
    C = data.draw(_nonzero_column_matrix(n_rows, n_cols))

    signs = canonical_component_signs(C)
    assert set(np.unique(signs)).issubset({-1.0, 1.0})

    C_signed = C * signs
    max_idx = np.argmax(np.abs(C_signed), axis=0)
    assert np.all(C_signed[max_idx, np.arange(n_cols)] >= 0)

    # Applying the canonical sign to an already-canonicalized matrix is a
    # no-op (all signs come back +1).
    signs_again = canonical_component_signs(C_signed)
    np.testing.assert_array_equal(signs_again, np.ones(n_cols))


def _mock_adata(A, B, C, weights, projections):
    n_cells = projections.shape[0]
    n_genes = C.shape[0]
    n_conditions = A.shape[0]
    obs = {"Condition": [f"cond_{i % n_conditions}" for i in range(n_cells)]}
    var = {"gene_name": [f"gene_{j}" for j in range(n_genes)]}
    return anndata.AnnData(
        obs=obs,
        var=var,
        uns={"Pf2_A": A, "Pf2_B": B, "Pf2_weights": weights},
        varm={"Pf2_C": C},
        obsm={"projections": projections},
    )


@given(
    rank=st.integers(min_value=1, max_value=5),
    n_conditions=st.integers(min_value=1, max_value=6),
    n_genes=st.integers(min_value=2, max_value=15),
    n_cells=st.integers(min_value=3, max_value=20),
    seed=st.integers(min_value=0, max_value=2**31 - 1),
)
@_slow_settings
def test_order_components_by_energy_is_a_permutation(
    rank, n_conditions, n_genes, n_cells, seed
):
    """For any shape/seed, reordering by energy must: (1) leave energy sorted
    descending, and (2) be a genuine permutation of the original columns --
    weighted_projections after reordering must equal the original
    weighted_projections with columns permuted (order_components_by_energy
    keeps B as the unflipped sign reference, so this holds exactly)."""
    rng = np.random.default_rng(seed)
    A = rng.normal(size=(n_conditions, rank))
    C = rng.normal(size=(n_genes, rank)) + np.eye(n_genes, rank) * 10.0
    B = rng.normal(size=(rank, rank))
    weights = rng.random(rank)
    if rank <= n_cells:
        projections, _ = np.linalg.qr(rng.normal(size=(n_cells, rank)))
    else:
        projections = rng.normal(size=(n_cells, rank))

    before_wp = projections @ B
    adata = _mock_adata(A.copy(), B.copy(), C.copy(), weights.copy(), projections)

    ordered = order_components_by_energy(adata)

    new_A = np.array(ordered.uns["Pf2_A"])
    new_C = np.array(ordered.varm["Pf2_C"])
    new_weights = np.array(ordered.uns["Pf2_weights"])
    new_energy = (
        np.abs(new_weights)
        * np.linalg.norm(new_A, axis=0)
        * np.linalg.norm(new_C, axis=0)
    )
    assert np.all(np.diff(new_energy) <= 1e-6)

    energy = np.abs(weights) * np.linalg.norm(A, axis=0) * np.linalg.norm(C, axis=0)
    order = np.argsort(energy)[::-1]
    np.testing.assert_allclose(
        np.array(ordered.obsm["weighted_projections"]), before_wp[:, order], atol=1e-5
    )
    np.testing.assert_allclose(new_A.shape, A.shape)


@given(
    n_genes=st.integers(min_value=2, max_value=15),
    rank=st.integers(min_value=1, max_value=6),
    seed=st.integers(min_value=0, max_value=2**31 - 1),
)
@_slow_settings
def test_match_components_across_ranks_self_match_is_identity(n_genes, rank, seed):
    """Matching a (sign-canonicalized) gene factor matrix against an
    identical copy of itself must recover the identity permutation with
    every component matched -- the base case any correct matching
    implementation has to satisfy."""
    rng = np.random.default_rng(seed)
    C = rng.normal(size=(n_genes, rank)) + np.eye(n_genes, rank) * 10.0
    C = C * canonical_component_signs(C)

    matched_pairs, unmatched_high = match_components_across_ranks(C, C.copy())

    assert matched_pairs.shape[0] == rank
    assert unmatched_high.size == 0
    np.testing.assert_array_equal(np.sort(matched_pairs[:, 0]), np.arange(rank))
    np.testing.assert_array_equal(np.sort(matched_pairs[:, 1]), np.arange(rank))


@given(
    n_conditions=st.integers(min_value=2, max_value=8),
    rank=st.integers(min_value=1, max_value=5),
    scale=st.floats(min_value=0.1, max_value=50.0, allow_nan=False),
    seed=st.integers(min_value=0, max_value=2**31 - 1),
)
@_slow_settings
def test_correct_conditions_is_invariant_to_uniform_rescaling(
    n_conditions, rank, scale, seed
):
    """correct_conditions fits an intercept-including linear regression of
    the (geometric-mean) condition factor magnitude against read counts,
    then divides by the fit. Ordinary least squares is equivariant under
    scaling its target by a positive constant c (both the fitted slope and
    intercept scale by c), so the c introduced by rescaling Pf2_A cancels
    against the c picked up by the fitted correction term: the corrected
    output must be unchanged, for *any* underlying count data."""
    rng = np.random.default_rng(seed)
    n_cells_per_cond = 5
    n_cells = n_conditions * n_cells_per_cond
    n_genes = 8

    cond_idx = np.repeat(np.arange(n_conditions), n_cells_per_cond)
    counts_X = rng.integers(1, 50, size=(n_cells, n_genes)).astype(np.float64)
    A = rng.uniform(0.1, 10.0, size=(n_conditions, rank))

    def _make(A_):
        adata = anndata.AnnData(X=counts_X.copy())
        adata.obs["condition_unique_idxs"] = cond_idx
        adata.uns["Pf2_A"] = A_
        return adata

    baseline = correct_conditions(_make(A.copy()))
    scaled = correct_conditions(_make(A.copy() * scale))

    np.testing.assert_allclose(scaled, baseline, rtol=1e-4, atol=1e-6)


@pytest.mark.parametrize("D", [8, 16])
def test_opq_reconstruction_r2_nondecreasing_in_num_subquantizers(D):
    """Fidelity (R^2) must not get worse as the projection matrix is split
    into more, finer-grained sub-quantizers -- more codebooks can only add
    representational capacity."""
    rng = np.random.default_rng(0)
    N = 300
    P = rng.normal(size=(N, D)).astype(np.float32)
    P, _ = np.linalg.qr(P)

    prev_r2 = -np.inf
    for M in sorted({1, 2, 4, D}):
        if M > D:
            continue
        q = OPQQuantizer(M=M, random_state=0)
        _, _, r2 = q.fit_transform(P)
        # A small numerical slack: OPQ's alternating optimization is a
        # heuristic, not an exact solver, so strict monotonicity can be
        # violated by noise near saturation (r2 close to 1).
        assert r2 >= prev_r2 - 0.05
        prev_r2 = r2
