name: Build

on: [push]
concurrency: gpu

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: poetry install
    - name: Build figures
      run: make all
    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: files
        path: |
          output/*.png
