# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: rye install
    - name: Run pyright check
      run: make pyright
    - name: Run ruff check
      run: rye fmt check sccp
    - name: Run ruff format check
      run: rye fmt --check sccp
    - name: Test with pytest
      run: make coverage.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
